#!/bin/bash
set -e

cd spec/dummy

cleanup() {
  cd ../..
  exit 0
}

# Set trap to cleanup on script exit
trap cleanup EXIT INT TERM

URL="http://localhost:3000/"
COUNT=50
SUM=0

for i in $(seq 1 $COUNT); do
  TTFB=$(curl -o /dev/null -s -w '%{time_starttransfer}\n' "$URL")
  SUM=$(echo "$SUM + $TTFB" | bc)
done

AVG=$(echo "scale=4; $SUM / $COUNT" | bc)
echo "Average TTFB: $AVG"
